### ISSUE TITLE
Kotlin missing in Lines of Code

### ISSUE THREAD

**Issue by saitho** [arturbosch/sonar-kotlin#10]
I just installed your Kotlin Plugin on my Sonarqube-Server and I noticed that only XML shows up in the "Lines of Code" area. I also tried a new project import.

**Comment by arturbosch** [comment]
Thank you for trying this out! Do you have an idea how to fix this? Sonar plugins are pretty new to me but there is a good groovy plugin to look at.

**Comment by saitho** [comment]
I'm also new to Sonarqube, sorry. ^^ So far I've only used it once for a Java project in university...

**Comment by arturbosch** [comment]
But this metric (well logical lines of code) is also collected by plain detekt. Soon sloc and loc too so I can add custom sonar metrics to the report ^^

**Comment by vexdev** [comment]
Actually it looks to me that you are not setting the `CoreMetrics.LINES`, `CoreMetrics.NCLOC` and `CoreMetrics.COMMENT_LINES`, that are per-file metrics. This results in sonarqube understanding the overall LOCs but missing per-file details, which are also a pre-requisite for JaCoCo or other code coverage tools to work.

I tried implementing those metrics but from your previous comment I understand that those are already collected from Detekt. If so, I don't get how to extract it from detekt-api, maybe you can enlighten me?

Otherwise, I think the best place to extract those metrics would maybe be `KotlinSyntax`, but there you are going trough the file token by token which prevents simple line counting :)

**Comment by emartynov** [comment]
Luca, I wonder if you have a reference for sonar plugin documentation or at least sonar itself.

**Comment by vexdev** [comment]
Oh no I apologise, apparently the documentation is not the best, what I have is:
https://docs.sonarqube.org/display/DEV/Supporting+New+Languages
And the groovy plugin mentioned by Artur:
https://github.com/SonarQubeCommunity/sonar-groovy/tree/master/sonar-groovy-plugin/src/main/java/org/sonar/plugins/groovy

That actually is a good starting point.

**Comment by emartynov** [comment]
That is where from I copied code but it is real monkey guessing job :)

**Comment by vexdev** [comment]
Ok I managed to get sloc and comments counted, will open a PR tomorrow so we can try to also run the jacoco branch. But now I also believe the complexity measure is quite prioritary.

**Comment by arturbosch** [comment]
Hey, sorry for the late response. 

Yes, the loc, sloc,  cloc and lloc are counted by detekt and can be retrieved from the detection result `detektion.getData(Key<T>)`. The keys are stored inside the `.../core/processors` files. The McCabe complexity is also calculated by detekt, see `COMPLEXITY_KEY` and `ComplexityVisitor`.

I'm looking forward to your PR!

**Comment by vexdev** [comment]
PR: https://github.com/arturbosch/sonar-kotlin/pull/26

**Comment by arturbosch** [comment]
Merged and works fine, together with other detekt project metrics we now have some measurements, thanks! :)
