### ISSUE TITLE
sonarqube v5.6.1 : plugin v0.2.4 : gradle task fails with > Call ofType() first

### ISSUE THREAD

**Issue by diarmuidkeane** [arturbosch/sonar-kotlin#40]
:sonarqube
Analyzing 18 kotlin files: 
:sonarqube FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> Call ofType() first

will see if I can get a full stack-trace ( tricky as its our prod sonarqube and plugin was backed out )

**Comment by arturbosch** [comment]
Yeah a full stack-trace would be good. `Call ofType() first` does not tell me anything unfortunately...

**Comment by Neristance** [comment]
I guess i can help with the stacktrace:

`Exception is:
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sonarqube'.
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NullPointerException: Call ofType() first
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.api.internal.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.api.batch.sensor.coverage.internal.DefaultCoverage.doSave(DefaultCoverage.java:142)
10:50:48.758 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJacocoReportAnalyzer.readExecutionData(KotlinJacocoReportAnalyzer.kt:123)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJacocoReportAnalyzer.analyse(KotlinJacocoReportAnalyzer.kt:84)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor.execute(KotlinJaCoCoSensor.kt:68)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.proxy.$Proxy679.execute(Unknown Source)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:99)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
10:50:48.759 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 29 more`

**Comment by Neristance** [comment]
Just a small adition for me it happens on Sonarqube: Version 5.6.6 and Gradle Plugin 2.6.1

**Comment by peerke** [comment]
I seem to have the same problem. I already had the plugin running on a project with only Kotlin code and that was working without problems. Now with a second project I converted one Java class into Kotlin and I get the same error. 

Using the following:
Compiled version of the plugin of today (december 13th)
Kotlin 1.2.0
SonarQube Gradle plugin 2.6.1
SonarQube 5.6.6

**Comment by Neristance** [comment]
You can remove Jacoco Reports then it does work, at least for me it did but still missing the testcoverage would be nice to have a fix

**Comment by peerke** [comment]
That is not really an option for me. For now I stick to Java code. I will start using Kotlin when this issue will be resolved.

**Comment by arturbosch** [comment]
Ok the exception was due to some specific method which had to be called when using 5.6 LTS of sonar. Please review if it now works for you, thanks!
PS: 5.6 is not LTS anymore. So we will just support the new 6.7 LTS in the future.

**Comment by peerke** [comment]
I tested against the latest master and I can confirm the issue has been resolved! Thanks a lot for the fast fix!

P.s. I saw today that SonarQube 6.7 LTS came out, so I guess that I will upgrade to that one when I have some more time.

**Comment by mfriedenhagen** [comment]
Just a note here: dashboards are not supported anymore in 6.7

Regards
Mirko
-- 
Sent from my mobile

Am 15.12.2017 16:20 schrieb "Peter" <notifications@github.com>:

**Comment by arturbosch** [comment]
hey @mfriedenhagen , just saw that you spend some time on configuring jacoco [here](https://github.com/mfriedenhagen/kotlin-sonar). In #48 I've tried to copy sonar-groovy's way of doing jacoco. Unfortunately I'am getting ```cannot set coverage Line 57 is out of range in the file src/main/kotlin/io/gitlab/arturbosch/detekt/sonar/foundation/KotlinSyntax.kt (lines: 56)``` ... some idea?

**Comment by diarmuidkeane** [comment]
Can also confirm that issue is resolved . Thanks to the Author and to all contributors

**Comment by mfriedenhagen** [comment]
Works here as well. Thanks.
